import ContentLoader from 'react-content-loader'

const BoardLoader = ({ ...props }) => {
    return (
        <div className='flex justify-center gap-x-4 py-4 px-6 h-full min-w-max'>
            <ContentLoader
                speed={1.5}
                width={280}
                height={280}
                viewBox='0 0 280 280'
                backgroundColor='#cbd4db4d'
                foregroundColor='#cbd4db'
                {...props}
            >
                <rect
                    x='222'
                    y='1'
                    rx='3'
                    ry='3'
                    width='28'
                    height='28'
                />
                <rect
                    x='1'
                    y='1'
                    rx='3'
                    ry='3'
                    width='220'
                    height='28'
                />
                <rect
                    x='252'
                    y='1'
                    rx='3'
                    ry='3'
                    width='28'
                    height='28'
                />
                <rect
                    x='0'
                    y='50'
                    rx='3'
                    ry='3'
                    width='280'
                    height='75'
                />
                <rect
                    x='0'
                    y='135'
                    rx='3'
                    ry='3'
                    width='280'
                    height='100'
                />
                <rect
                    x='0'
                    y='245'
                    rx='3'
                    ry='3'
                    width='280'
                    height='36'
                />
            </ContentLoader>
            <ContentLoader
                speed={1.5}
                width={280}
                height={280}
                viewBox='0 0 280 280'
                backgroundColor='#cbd4db4d'
                foregroundColor='#cbd4db'
                {...props}
            >
                <rect
                    x='222'
                    y='1'
                    rx='3'
                    ry='3'
                    width='28'
                    height='28'
                />
                <rect
                    x='1'
                    y='1'
                    rx='3'
                    ry='3'
                    width='220'
                    height='28'
                />
                <rect
                    x='252'
                    y='1'
                    rx='3'
                    ry='3'
                    width='28'
                    height='28'
                />
                <rect
                    x='0'
                    y='50'
                    rx='3'
                    ry='3'
                    width='280'
                    height='75'
                />
                <rect
                    x='0'
                    y='135'
                    rx='3'
                    ry='3'
                    width='280'
                    height='36'
                />
            </ContentLoader>
        </div>
    )
}

export default BoardLoader
